import { myBgImage1, myBgImage2, myBgImage3 } from "./imageImport";

// generate random number from 1 - 3
function randomNumber() {
    return Math.floor(Math.random() * 3) + 1;
}

// this func. change bg_image base on the random number generated by the func. above
function ImageChanger() {
    
    let image_url = [
        myBgImage1,
        myBgImage2,
        myBgImage3
    ]

    if(randomNumber() === 1) {
        return image_url[0]
    } else if (randomNumber() === 2) {
        return image_url[1]
    } else {
        return image_url[2]
    }
}

// func. that change the bg_image after the event is triggered
export function changeBackgroundImageOnHover() {
        const contentDiv = document.getElementById('content')
        contentDiv.addEventListener('mouseover', (e) => {
            e.preventDefault();
            contentDiv.style.backgroundImage = `url(${ImageChanger()})`;
    })
}




